- name: Install sudo
  apt:
    name: sudo
    state: latest

- name: Update repositories
  shell: |
    apt-get clean
    apt-get update
    apt-get -y upgrade
  become: true

- name: Install git
  apt:
    name: git
    state: latest

- name: Install htop
  apt:
    name: htop
    state: latest

- name: Install mc
  apt:
    name: mc
    state: latest

- name: Install docker
  script: docker_install_script.sh

- name: Install docker-compose
  shell: |
    curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install letsencrypt
  apt:
    name: letsencrypt
    state: latest

- name: Create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Remove default nginx virtual host
  file:
    path: '{{ nginx__sites_available_dir }}/default'
    state: absent
  notify: reload nginx

- name: Install system nginx config
  template:
    src: '{{ nginx__nginx_conf_template }}'
    dest: /etc/nginx/nginx.conf

- name: Install nginx site for letsencrypt requests
  template:
    src: '{{ nginx__host_letsencrypt_template }}'
    dest: '{{ nginx__sites_enabled_dir }}/{{ nginx__host_letsencrypt_filename }}'

- name: Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Create nginx virtual host
  template:
    src: '{{ nginx__host_site_template }}'
    dest: '{{ nginx__sites_available_dir }}/{{ nginx__host_site_filename }}'
  notify: reload nginx

- name: Create symbolic link for virtual host
  file:
    src: '{{ nginx__sites_available_dir }}/{{ nginx__host_site_filename }}'
    dest: '{{ nginx__sites_enabled_dir }}/{{ nginx__host_site_filename }}'
    state: link
  notify: reload nginx

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain }} && service nginx reload

- name: Add php repository
  shell: |
    apt-get -y install apt-transport-https lsb-release ca-certificates
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
    apt-get update
    warn=no

- name: Install php7.1-fpm
  apt:
    name: php7.1-fpm

- name: Install php7.1-pdo-pgsql
  apt:
    name: php7.1-pdo-pgsql

- name: Install php7.1-dom
  apt:
    name: php7.1-dom

- name: Install php7.1-zip
  apt:
    name: php7.1-zip

- name: Install php7.1-mbstring
  apt:
    name: php7.1-mbstring

- name: Install php7.1-curl
  apt:
    name: php7.1-curl

- name: Uncomment listen.mode in www.conf
  replace:
    path: '{{ php__www_conf }}'
    regexp: '^;listen.mode = 0660$'
    replace: 'listen.mode = 0660'
  notify: restart php-fpm

- name: Update post_max_size in php.ini
  replace:
    path: '{{ php__php_ini }}'
    regexp: '^post_max_size = [0-9]+M'
    replace: 'post_max_size = 128M'
  notify: restart php-fpm

- name: Update upload_max_filesize in php.ini
  replace:
    path: '{{ php__php_ini }}'
    regexp: '^upload_max_filesize = [0-9]+M'
    replace: 'upload_max_filesize = 100M'
  notify: restart php-fpm

- name: Install postgresql
  shell: |
    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    apt-get update
    apt-get install postgresql-10 -y
  notify: restart postgresql

- name: Install postgresql adapter # todo: Что это и зачем?
  apt:
    name: python-psycopg2
    state: present

- name: Create postgresql user
  postgresql_user:
    name: '{{ postgres__user }}'
    password: '{{ postgres__password }}'
    encrypted: yes
  become: true
  become_user: postgres
  notify: restart postgresql

- name: Create postgresql database
  postgresql_db:
    name: '{{ postgres__database }}'
    owner: '{{ postgres__user }}'
  become: true
  become_user: postgres
  notify: restart postgresql

- name: Copy pg_hba.conf
  copy:
    src: '{{ postgres__pg_hba_conf }}'
    dest: '/etc/postgresql/10/main/pg_hba.conf'
  notify: restart postgresql

- name: Make postgresql start automatically on boot
  systemd:
    name: postgresql
    enabled: yes