security:
    providers:
#        jwt_user_provider:
#            lexik_jwt:
#                class: App\Entity\User
        main:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_user_register:
            pattern: ^/api/user/register
            anonymous: true
        api_token_create:
            pattern: ^/api/token/create
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/token/create
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
            provider: main
#        api_token_refresh:
#            pattern: ^/api/token/refresh
#            stateless: true
#            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            provider: main
        main:
            anonymous: true
    access_control:
        - { path: ^/api/user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
