monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: handlers_group
            channels: ['!event']
        handlers_group:
            type: group
            members:
                - nested
                - papertrail
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        papertrail:
            type: socket
            connection_string: 'tls://%env(resolve:PAPERTRAIL_HOST)%:%env(resolve:PAPERTRAIL_PORT)%'
            level: error
            max_files: 14
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ['php']